spring:
  datasource:
    password: root
    username: root
    url: jdbc:h2:mem:webspider_db_dev
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

store:
  uri: https://store.playstation.com/pt-br/grid/STORE-MSF77008-ALLGAMES/
  firstPage: 1
  defaultTotalPages: 235
