spring:
  datasource:
    password: root
    username: root
    url: jdbc:h2:mem:webspider_db_dev
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://35.203.35.28:8761/eureka

store:
  domain: https://store.playstation.com/
  uri: pt-br/category/44d8bb20-653e-431e-8ad0-c0a365f68d2f/
  firstPage: 1
  defaultTotalPages: 89
